name: aharrisvg
favicon: null
layout_spectrum: 0.94949
typography_spectrum: 0.17909
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3f3f3f'
    - '#7a7e81'
    - '#c8c8c8'
    - '#fe6cbf'
  brandStrength: 0.625
  lightness: 0.1875
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
